language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3
node_js:
  - "12.2.0"
before_install:
  - npm install npm -g
before_script:
  - npm install -g grunt-cli
script:
  - npm run-script ci
